COMMON SHARED fezload
COMMON SHARED PosxT
COMMON SHARED PosyT
COMMON SHARED corfundo
SCREEN 13
LINE (1, 1)-(16, 17), 15, BF
LINE (5, 1)-(9, 1), 0
LINE (3, 2)-(4, 2), 0
LINE (2, 3)-(2, 3), 0
LINE (1, 4)-(1, 7), 0
LINE (2, 8)-(3, 9), 0, BF
LINE (4, 9)-(10, 9), 0
LINE (11, 8)-(12, 9), 0, BF
LINE (13, 4)-(13, 7), 0
LINE (12, 3)-(12, 3), 0
LINE (10, 2)-(11, 2), 0
LINE (1, 10)-(1, 11), 0
LINE (13, 10)-(13, 11), 0
LINE (2, 12)-(2, 12), 0
LINE (12, 12)-(12, 12), 0
LINE (4, 11)-(10, 11), 0
LINE (3, 10)-(3, 15), 0
LINE (11, 10)-(11, 15), 0
LINE (4, 10)-(4, 10), 0
LINE (10, 10)-(10, 10), 0
LINE (4, 16)-(6, 16), 0
LINE (8, 16)-(10, 16), 0
LINE (7, 15)-(7, 15), 0
LINE (4, 14)-(10, 14), 0
LINE (2, 6)-(5, 6), 0
LINE (6, 7)-(7, 7), 0
LINE (8, 6)-(12, 6), 0
PAINT (6, 4), 14, 0
PAINT (7, 13), 40, 0
PAINT (5, 15), 9, 0
PAINT (9, 15), 9, 0
fezload = 1
PosxT = 16
PosyT = 17
corfundo = 15
CHAIN "GRAFICOE.BAS"

